### ISSUE TITLE
Loadstone compass with different locations stack and show the same direction

### ISSUE THREAD

**Issue by jusobreira** [MineVid/dtlTraders-plus-#10]
When i try to trade  3 compass with 3 Loadstones locations in  3 different trades, the trade completes even if i have another loadstone compass with another location set.  The metadata are been ignored. 
![image](https://user-images.githubusercontent.com/10175304/121580682-67326280-ca03-11eb-81b7-3ba2decbbe0a.png)

![image](https://user-images.githubusercontent.com/10175304/121580730-75807e80-ca03-11eb-9c24-408aa7b96bb7.png)

I can trade as many as i want with other compass locations

In those prints i'm using the same compass to trade 3 different compass

![image](https://user-images.githubusercontent.com/10175304/121580767-8204d700-ca03-11eb-947f-7ba663486567.png)

![image](https://user-images.githubusercontent.com/10175304/121580861-9a74f180-ca03-11eb-8763-0c995ea04c54.png)

```
testes:
  title: testes
  command: none
  permission: none
  default-shop: buy
  buy-shop-enabled: true
  sell-shop-enabled: true
  trade-shop-enabled: true
  logging-enabled: true
  close-after-purchase: false
  confirmation-window-enabled: false
  pages:
    page-0:
      size: 54
      page-name: '1'
      page-permission: ''
      trade-items:
        item-1:
          id: 15
          type: trade
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GRASS_BLOCK
          show-description: true
          description: []
          trade-price: 0.0
          show-obtainable-items: true
          obtainable-items:
            obtainable-item-1:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: GRASS_BLOCK
          show-needed-items: true
          needed-items:
            trade-item-0:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: COMPASS
                meta:
                  ==: ItemMeta
                  meta-type: COMPASS
                  LodestonePosWorld: minecraft:azenzo
                  LodestonePosX: 78
                  LodestonePosY: 4
                  LodestonePosZ: -37
                  LodestoneTracked: true
          show-trade-limit: false
          trade-limit: -1
          show-limit-time: false
          limit-reset-seconds: -1
          show-broadcast-message: false
          broadcast-message: ''
          drop-item-on-full-inventory: false
          sell-all-when-not-enough-items: true
          custom-display-text-enabled: false
          custom-display-text: []
          permission: ''
          logging-enabled: true
          close-after-purchase: false
        item-2:
          id: 16
          type: trade
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GRASS_BLOCK
          show-description: true
          description: []
          trade-price: 0.0
          show-obtainable-items: true
          obtainable-items:
            obtainable-item-11:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: COMPASS
                meta:
                  ==: ItemMeta
                  meta-type: COMPASS
                  LodestonePosWorld: minecraft:azenzo
                  LodestonePosX: 100
                  LodestonePosY: 4
                  LodestonePosZ: -41
                  LodestoneTracked: true
          show-needed-items: true
          needed-items:
            trade-item-11:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: GRASS_BLOCK
          show-trade-limit: false
          trade-limit: -1
          show-limit-time: false
          limit-reset-seconds: -1
          show-broadcast-message: false
          broadcast-message: ''
          drop-item-on-full-inventory: false
          sell-all-when-not-enough-items: true
          custom-display-text-enabled: false
          custom-display-text: []
          permission: ''
          logging-enabled: true
          close-after-purchase: false
        item-3:
          id: 17
          type: trade
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: GRASS_BLOCK
          show-description: true
          description: []
          trade-price: 0.0
          show-obtainable-items: true
          obtainable-items:
            obtainable-item-21:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: GRASS_BLOCK
          show-needed-items: true
          needed-items:
            trade-item-12:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: COMPASS
                meta:
                  ==: ItemMeta
                  meta-type: COMPASS
                  LodestonePosWorld: minecraft:azenzo
                  LodestonePosX: 87
                  LodestonePosY: 4
                  LodestonePosZ: -34
                  LodestoneTracked: true
          show-trade-limit: false
          trade-limit: -1
          show-limit-time: false
          limit-reset-seconds: -1
          show-broadcast-message: false
          broadcast-message: ''
          drop-item-on-full-inventory: false
          sell-all-when-not-enough-items: true
          custom-display-text-enabled: false
          custom-display-text: []
          permission: ''
          logging-enabled: true
          close-after-purchase: false
        item-20:
          id: 9
          type: trade
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: LODESTONE
          show-description: true
          description: []
          trade-price: 0.0
          show-obtainable-items: true
          obtainable-items:
            obtainable-item-22:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: ENCHANTED_BOOK
                meta:
                  ==: ItemMeta
                  meta-type: ENCHANTED
                  stored-enchants:
                    BINDING_CURSE: 1
          show-needed-items: true
          needed-items:
            trade-item-21:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: COMPASS
                meta:
                  ==: ItemMeta
                  meta-type: COMPASS
                  LodestonePosWorld: minecraft:azenzo
                  LodestonePosX: 78
                  LodestonePosY: 4
                  LodestonePosZ: -37
                  LodestoneTracked: true
            trade-item-23:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: COMPASS
                meta:
                  ==: ItemMeta
                  meta-type: COMPASS
                  LodestonePosWorld: minecraft:azenzo
                  LodestonePosX: 78
                  LodestonePosY: 4
                  LodestonePosZ: -37
                  LodestoneTracked: true
          show-trade-limit: false
          trade-limit: -1
          show-limit-time: false
          limit-reset-seconds: -1
          show-broadcast-message: false
          broadcast-message: ''
          drop-item-on-full-inventory: false
          sell-all-when-not-enough-items: true
          custom-display-text-enabled: false
          custom-display-text: []
          permission: ''
          logging-enabled: true
          close-after-purchase: false
        item-24:
          id: 11
          type: trade
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: ENCHANTED_BOOK
            meta:
              ==: ItemMeta
              meta-type: ENCHANTED
              repair-cost: 1
              stored-enchants:
                PROTECTION_FIRE: 4
          show-description: true
          description: []
          trade-price: 10.0
          show-obtainable-items: true
          obtainable-items:
            obtainable-item-22:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: BEACON
          show-needed-items: true
          needed-items:
            trade-item-21:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: ENCHANTED_BOOK
                meta:
                  ==: ItemMeta
                  meta-type: ENCHANTED
                  repair-cost: 1
                  stored-enchants:
                    PROTECTION_FIRE: 4
            trade-item-22:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2586
                type: ENCHANTED_BOOK
                meta:
                  ==: ItemMeta
                  meta-type: ENCHANTED
                  repair-cost: 1
                  stored-enchants:
                    PROTECTION_FIRE: 4
          show-trade-limit: false
          trade-limit: -1
          show-limit-time: false
          limit-reset-seconds: -1
          show-broadcast-message: false
          broadcast-message: ''
          drop-item-on-full-inventory: false
          sell-all-when-not-enough-items: true
          custom-display-text-enabled: false
          custom-display-text: []
          permission: ''
          logging-enabled: true
          close-after-purchase: false

```
